apiVersion: v1
kind: Secret
metadata:
  name: orocommerce-secret
  namespace: orocommerce
type: Opaque
data:
  ORO_USER_RUNTIME: d3d3LWRhdGE=
  ORO_ENV: cHJvZA==

  ORO_USER_NAME: YWRtaW4=
  ORO_USER_PASSWORD: YWRtaW4=
  ORO_USER_FIRSTNAME: Sm9obg==
  ORO_USER_LASTNAME: RG9l
  ORO_USER_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=
  ORO_SAMPLE_DATA: eQ==
  ORO_ORGANIZATION_NAME: T1JP
  ORO_FORMATTING_CODE: ZnJfRlI=
  ORO_APP_PROTOCOL: aHR0cA==
  ORO_APP_DOMAIN: b3JvLmRlbW8=
  ORO_WEB_HOST: b3JvY29tbWVyY2Utbmdpbng=
  ORO_NGINX_HTTP_PORT: ODA=

  ORO_MULTIHOST_OPERATION_FOLDER: L3Zhci93d3cvb3JvL3Zhci9tdWx0aWhvc3Q=
  ORO_MAINTENANCE_LOCK_FOLDER: L3Zhci93d3cvb3JvL3Zhci9tYWludGVuYW5jZQ==
  ORO_MAINTENANCE_LOCK_FILE_NAME: bWFpbnRlbmFuY2VfbG9jaw==
  ORO_MAINTENANCE_LOCK_FILE_PATH: L3Zhci93d3cvb3JvL3Zhci9tYWludGVuYW5jZS9tYWludGVuYW5jZV9sb2Nr

  ORO_PHP_FPM_HOST: b3JvY29tbWVyY2UtYXBwLXBocC1mcG0=
  ORO_PHP_FPM_PORT: OTAwMA==
  ORO_CONSUMER_SERVICE: Y29uc3VtZXI=
  ORO_PAUSE_SERVICES: cGhwLWZwbS1hcHB8Y3Jvbg==
  ORO_RESTART_SERVICES: cGhwLWZwbS1hcHB8Y3Jvbnx3cw==
  ORO_DEBUGGER: LW5v
  ORO_DB_VERSION: MTcuMg==
  ORO_PG_VER: MTcuMi1hbHBpbmU=

  ORO_DB_HOST: b3JvY29tbWVyY2UtZGI=
  ORO_DB_PORT: NTQzMg==
  ORO_DB_NAME: b3JvZGI=
  ORO_DB_USER: b3JvZGJ1c2Vy
  ORO_DB_PASSWORD: b3JvZGJwYXNz
  ORO_DB_DSN: cG9zdGdyZXM6Ly9vcm9kYnVzZXI6b3JvZGJwYXNzQG9yb2NvbW1lcmNlLWRiOjU0MzIvb3JvZGI/c3NsbW9kZT1kaXNhYmxlJmNoYXJzZXQ9dXRmOCZzZXJ2ZXJWZXJzaW9uPTE3LjI=
  ORO_DB_ROOT_USER: b3JvZGJ1c2Vy
  ORO_DB_ROOT_PASSWORD: b3JvZGJwYXNz

  ORO_MQ_DSN: ZGJhbDo=
  ORO_SESSION_DSN: bmF0aXZlOg==
  ORO_SEARCH_ENGINE_DSN: b3JtOj9wcmVmaXg9b3JvX3NlYXJjaA==
  ORO_WEBSITE_SEARCH_ENGINE_DSN: b3JtOj9wcmVmaXg9b3JvX3dlYnNpdGVfc2VhcmNo
  ORO_MAILER_DSN: c210cDovL21haWw6MTAyNQ==
  ORO_WEBSOCKET_BACKEND_HOST: b3JvY29tbWVyY2Utd2Vic29ja2V0
  ORO_WEBSOCKET_BACKEND_PORT: ODA4MA==
  ORO_WEBSOCKET_SERVER_DSN: Ly8wLjAuMC4wOjgwODA=
  ORO_WEBSOCKET_FRONTEND_DSN: Ly8qOjgwL3dz
  ORO_WEBSOCKET_BACKEND_DSN: dGNwOi8vb3JvY29tbWVyY2Utd2Vic29ja2V0OjgwODA=

  ORO_APP_URL: aHR0cDovL29yby5kZW1v
  ORO_SITES: eyJvcm8uZGVtbyI6eyJkb21haW5fZGlyZWN0IjpmYWxzZSwibG9jYXRpb25zX21lcmdlIjp0cnVlfX0=
  ORO_GLOBAL_HTTP_PORT: ODA=
  ORO_GLOBAL_SHARED_ROOT_DIR: L3Zhci93d3cvb3JvL3Zhci9tYWludGVuYW5jZQ==
  ORO_GLOBAL_LOCK_FILE_PATH: L3Zhci93d3cvb3JvL3Zhci9tYWludGVuYW5jZS9nbG9iYWxfbG9jaw==
  ORO_GLOBAL_USE_UPSTREAM: dHJ1ZQ==
  ORO_GLOBAL_LIMIT_REQ_ENABLE: ZmFsc2U=
  ORO_GLOBAL_TESTCOOKIE_ENABLE: ZmFsc2U=
  ORO_HTTP_UPSTREAM: eyJhcHAiOnsic2VydmVycyI6W3siaG9zdCI6Im9yb2NvbW1lcmNlLWFwcC1waHAtZnBtIiwicG9ydCI6IDkwMDB9XX0sIndzIjp7InNlcnZlcnMiOlt7Imhvc3QiOiJvcm9jb21tZXJjZS13ZWJzb2NrZXQiLCJwb3J0IjogODA4MH1dfX0=
  ORO_SERVER_LOCATION: eyJ+IC9pbmRleFxcLnBocCgvfCQpIjogeyJ0eXBlIjoicGhwIiwiZmFzdGNnaV9wYXJhbSI6IHsiSFRUUFMiOiAib2ZmIn19LCAiQHJld3JpdGUiOiB7InR5cGUiOiAibmFtZWQiLCAicmF3X3ByZXBlbmQiOiBbImlmICgtZiAvdmFyL3d3dy9vcm8vdmFyL21haW50ZW5hbmNlL2dsb2JhbF9sb2NrKSB7IGFkZF9oZWFkZXIgXCJDYWNoZS1Db250cm9sXCIgXCJuby1jYWNoZVwiOyByZXR1cm4gNTAzOyB9Il19fQ==

  HP_MEMORY_LIMIT: NjA5Nk0=

  ORO_LANGUAGE: ZnJfRlI=
  ORO_LANGUAGE_SUFFIX: LWZy
  ORO_APP_COUNTRY: RlI=
  ORO_APP_TIMEZONE: RXVyb3BlL1Bhcmlz
  ORO_APP_TEMPERATURE_UNIT: Y2Vsc2l1cw==
  ORO_APP_WIND_SPEED_UNIT: bWV0ZXJzX3Blcl9zZWNvbmQ=
  ORO_APP_CURRENCY: RVVS
