apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: "nfs.csi.k8s.io"
  share: /orocommerce
  csi.storage.k8s.io/provisioner-secret-namespace: "orocommerce"
volumeBindingMode: Immediate
reclaimPolicy: Retain
allowVolumeExpansion: false
mountOptions:
  - nfsvers=4.1