apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
  namespace: {{ default "orocommerce" .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: "init"
        image: {{ .Values.images.initContainer.repository }}:{{ .Values.images.initContainer.tag }}
        command: 
          - "sh"
          - "-c"
          - "until nc -z {{ .Release.Name }}-app 9000; do echo \"Waiting for php-fpm connection...\"; sleep 1; done && until nc -z {{ .Release.Name }}-websocket 8080; do echo \"Waiting for websocket connection...\"; sleep 1; done && /usr/local/bin/docker-entrypoint.sh nginx-init && sed -i '/gridfs/d; /mongo/d' /opt/oro-nginx/etc/sites-available/*.conf"
        envFrom:
          - secretRef: 
              name: {{ .Release.Name }}-secret
        volumeMounts:
          - name: {{ .Release.Name }}-nginx-pvc
            mountPath: /opt/oro-nginx
        {{- with .Values.initSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      containers:
      - name: "nginx"
        image: {{ .Values.images.container.repository }}:{{ .Values.images.container.tag }}
        ports:
          - containerPort: {{ .Values.service.port }}
            name: nginx
            protocol: TCP
        args: 
          - "nginx"
        envFrom:
          - secretRef: 
              name: {{ .Release.Name }}-secret
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        volumeMounts:
          - name: {{ .Release.Name }}-nginx-pvc
            mountPath: /opt/oro-nginx
          - name: {{ .Release.Name }}-app-pvc
            mountPath: /var/www/oro
          - name: {{ .Release.Name }}-app-cache-pvc
            mountPath: /var/www/oro/var/cache
          - name: {{ .Release.Name }}-app-maintenance-pvc
            mountPath: /var/www/oro/var/maintenance
          - name: {{ .Release.Name }}-app-public-pvc
            mountPath: /var/www/oro/public/media
          - name: {{ .Release.Name }}-app-private-pvc
            mountPath: /var/www/oro/var/data
      volumes:
        - name: {{ .Release.Name }}-nginx-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-nginx-pvc
        - name: {{ .Release.Name }}-app-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-pvc
            readOnly: false
        - name: {{ .Release.Name }}-app-cache-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-cache-pvc
            readOnly: true
        - name: {{ .Release.Name }}-app-maintenance-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-maintenance-pvc
            readOnly: false
        - name: {{ .Release.Name }}-app-public-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-public-pvc
            readOnly: true
        - name: {{ .Release.Name }}-app-private-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-private-pvc
            readOnly: true
