apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgre-pv
  labels:
    name: postgre-pv
  namespace: orocommerce
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /orocommerce/postgre