apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orocommerce-db
  labels:
    app: orocommerce-db
  namespace: orocommerce
spec:
  selector:
    matchLabels:
      app: orocommerce-db
  serviceName: orocommerce-db
  replicas: 1
  template:
    metadata:
      labels:
        app: orocommerce-db
    spec:
      containers:
        - name: postgre
          image: docker.io/oroinc/pgsql:17.2-alpine
          ports:
          - containerPort: 5432
            name: postgre
          env:
            - name: POSTGRES_ROOT_PASSWORD
              value: "orodbpass"
            - name: POSTGRES_DB
              value: "orodb"
            - name: POSTGRES_USER
              value: "orodbuser"
            - name: POSTGRES_PASSWORD
              value: "orodbpass"
          volumeMounts:
            - name: postgre-pvc
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - exec pg_isready -U orodbuser -d orodb
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - -e
              - |
                exec pg_isready -U orodbuser -d orodb
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: postgre-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 5Gi
        storageClassName: local
        