apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-websocket
  labels:
    app: {{ .Release.Name }}-websocket
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-websocket
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-websocket
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: "verify-connection"
          image: {{ .Values.images.initContainer.repository }}:{{ .Values.images.initContainer.tag }}
          command: 
            - "sh"
            - "-c"
            - "until nc -z {{ .Release.Name }}-app 9000; do echo \"Waiting for php-fpm connection...\"; sleep 1; done && until nc -z {{ .Release.Name }}-postgre 5432; do echo \"Waiting for database connection...\"; sleep 1; done"
      containers:
      - name: "websocket"
        image: {{ .Values.images.container.repository }}:{{ .Values.images.container.tag }}
        args: 
          - "websocket"
        ports:
          - containerPort: {{ .Values.service.port }}
            name: websocket
            protocol: TCP
        envFrom:
          - secretRef: 
              name: {{ .Release.Name }}-secret
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        volumeMounts:
          - name: {{ .Release.Name }}-app-pvc
            mountPath: /var/www/oro
          - name: {{ .Release.Name }}-app-cache-pvc
            mountPath: /var/www/oro/var/cache
          - name: {{ .Release.Name }}-app-maintenance-pvc
            mountPath: /var/www/oro/var/maintenance
          - name: {{ .Release.Name }}-app-public-pvc
            mountPath: /var/www/oro/public/media
          - name: {{ .Release.Name }}-app-private-pvc
            mountPath: /var/www/oro/var/data
      volumes:
        - name: {{ .Release.Name }}-app-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-pvc
            readOnly: false
        - name: {{ .Release.Name }}-app-cache-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-cache-pvc
            readOnly: false
        - name: {{ .Release.Name }}-app-maintenance-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-maintenance-pvc
            readOnly: false
        - name: {{ .Release.Name }}-app-public-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-public-pvc
            readOnly: false
        - name: {{ .Release.Name }}-app-private-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-private-pvc
            readOnly: false