apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-app-public-pvc
  namespace: {{ default "orocommerce" .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  accessModes:
    {{- with .Values.persistentVolumes.appPublicAccessModes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  resources:
    requests:
      storage: {{ default "10Gi" .Values.persistentVolumes.appPublicCapacity }}
  storageClassName: {{ default "local-storage" .Values.storageClass.name }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-app-public-pv