apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-app-private-pvc
spec:
  accessModes:
    {{- with .Values.persistentVolumes.appPrivateAccessModes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  resources:
    requests:
      storage: {{ default "10Gi" .Values.persistentVolumes.appPrivateCapacity }}
  storageClassName: {{ default "csi-hostpath-sc" .Values.storageClassName }}