apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-app-pvc
spec:
  accessModes:
    {{- with .Values.persistentVolumes.appAccessModes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  resources:
    requests:
      storage: {{ default "10Gi" .Values.persistentVolumes.appCapacity }}
  storageClassName: {{ .Release.Name }}-csi-hostpath-sc