apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-app-maintenance-pvc
spec:
  accessModes:
    {{- with .Values.persistentVolumes.appMaintenanceAccessModes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  resources:
    requests:
      storage: {{ default "10Gi" .Values.persistentVolumes.appMaintenanceCapacity }}
  storageClassName: {{ default "csi-hostpath-sc" .Values.storageClassName }}