apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-app-multihost-operation-pvc
spec:
  accessModes:
    {{- with .Values.persistentVolumes.appMultihostOperationAccessModes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  resources:
    requests:
      storage: {{ default "10Gi" .Values.persistentVolumes.appMultihostOperationCapacity }}
  storageClassName: {{ .Release.Name }}-csi-hostpath-sc