apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-csi-hostpath-sc
provisioner: {{ default "hostpath.csi.k8s.io" .Values.storageClass.provisioner }}
reclaimPolicy: {{ default "Retain" .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ default "Immediate" .Values.storageClass.volumeBindingMode }}