apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-deployment
  labels:
    app: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
      - name: websocket
        image: oroinc/runtime:6.1-latest
        command: ["websocket"]
        ports:
        - containerPort: 8080
          name: websocket
        env:
          - name: ORO_ENV
            value: "prod"
          - name: ORO_LOG_PATH
            value: "php://stderr"
          - name: ORO_DB_HOST
            value: "postgre"
          - name: ORO_DB_PORT
            value: "5432"
          - name: ORO_DB_NAME
            value: "orodb"
          - name: ORO_DB_USER
            value: "orodbuser"
          - name: ORO_DB_PASSWORD
            value: "orodbpass"
          - name: ORO_DB_DSN
            value: "postgres://orodbuser:orodbpass@postgre:5432/orodb?sslmode=disable&charset=utf8&serverVersion=17.2"
        volumeMounts:
        - name: php-fpm-app-pvc
          mountPath: /var/www/oro
        - name: php-fpm-cache-pvc
          mountPath: /var/www/oro/var/cache
        - name: php-fpm-maintenance-pvc
          mountPath: /var/www/oro/var/maintenance
        - name: php-fpm-public-storage-pvc
          mountPath: /var/www/oro/public/media
        - name: php-fpm-private-storage-pvc
          mountPath: /var/www/oro/var/data
      volumes:
      - name: php-fpm-app-pvc
        persistentVolumeClaim:
          claimName: php-fpm-app-pvc
      - name: php-fpm-cache-pvc
        persistentVolumeClaim:
          claimName: php-fpm-cache-pvc
      - name: php-fpm-maintenance-pvc
        persistentVolumeClaim:
          claimName: php-fpm-maintenance-pvc
      - name: php-fpm-public-storage-pvc
        persistentVolumeClaim:
          claimName: php-fpm-public-storage-pvc
      - name: php-fpm-private-storage-pvc
        persistentVolumeClaim:
          claimName: php-fpm-private-storage-pvc