apiVersion: v1
kind: Service
metadata:
  name: websocket
  labels:
    app: websocket
spec:
  selector:
    app: websocket
  ports:
  - port: 8080
    targetPort: 8080
    name: websocket
  type: ClusterIP
