apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orocommerce-app-maintenance-pvc
  namespace: orocommerce
spec:
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: orocommerce-csi-hostpath-sc