apiVersion: v1
kind: PersistentVolume
metadata:
  name: orocommerce-app-cache-pv
  labels:
    name: orocommerce-app-cache-pv
  namespace: orocommerce
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /orocommerce/cache