apiVersion: v1
kind: PersistentVolume
metadata:
  name: orocommerce-app-multihost-operation-pv
  namespace: orocommerce
  labels:
    name: orocommerce-app-multihost-operation-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  hostPath:
    path: /orocommerce/multihost-operation
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube