apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orocommerce-app-private-pvc
  namespace: orocommerce
spec:
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      name: orocommerce-app-private-pv