apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-fpm-multihost-operation-pv
  namespace: orocommerce
  labels:
    name: php-fpm-multihost-operation-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: nfs-server.orocommerce.svc.cluster.local#orocommerce#/orocommerce/php-fpm/multihost-operation
    volumeAttributes:
      server: nfs-server.orocommerce.svc.cluster.local
      share: /orocommerce/php-fpm/multihost-operation