apiVersion: v1
kind: PersistentVolume
metadata:
  name: orocommerce-nginx-pv
  namespace: orocommerce
  labels:
    name: orocommerce-nginx-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  hostPath:
    path: /orocommerce/nginx
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube