apiVersion: v1
kind: PersistentVolume
metadata:
  name: orocommerce-nginx-pv
  namespace: orocommerce
  labels:
    name: orocommerce-nginx-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /orocommerce/nginx