apiVersion: v1
kind: PersistentVolume
metadata:
  name: orocommerce-postgre-pv
  labels:
    name: orocommerce-postgre-pv
  namespace: orocommerce
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /orocommerce/postgre