apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-fpm-public-pv
  labels:
    name: php-fpm-public-pv
  namespace: orocommerce
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /orocommerce/php-fpm/public
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
                - docker-desktop