apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgre
  labels:
    app: {{ .Release.Name }}-postgre
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: postgre
  selector:
    app: {{ .Release.Name }}-postgre