apiVersion: batch/v1
kind: Job
metadata:
  name: orocommerce-app-restore-job
  namespace: orocommerce
spec:
  template:
    spec:
      initContainers:
        - name: volume-init
          image: oroinc/orocommerce-application:6.1.0
          args: ["-c", "cp -rp /var/www/oro/. /data && chown -R www-data:www-data /data"]
          volumeMounts:
          - name: orocommerce-app-pvc
            mountPath: /data
          - name: orocommerce-app-cache-pvc
            mountPath: /data/var/cache
          - name: orocommerce-app-public-pvc
            mountPath: /data/public/media
          - name: orocommerce-app-private-pvc
            mountPath: /data/var/private
          securityContext:
            runAsUser: 0
      containers:
        - name: restore
          image: oroinc/orocommerce-application-init-fr:6.1.0
          command: ["sh", "-c", "until nc -z orocommerce-postgre 5432; do echo \"Waiting for database connection...\"; sleep 1; done && docker-entrypoint.sh restore"]
          envFrom:
            - secretRef: 
                name: orocommerce-secret
          volumeMounts:
          - name: orocommerce-app-pvc
            mountPath: /var/www/oro
          - name: orocommerce-app-cache-pvc
            mountPath: /var/www/oro/var/cache
          - name: orocommerce-app-public-pvc
            mountPath: /var/www/oro/public/media
          - name: orocommerce-app-private-pvc
            mountPath: /var/www/oro/var/data
      restartPolicy: Never
      volumes:
        - name: orocommerce-app-pvc
          persistentVolumeClaim:
            claimName: orocommerce-app-pvc
            readOnly: false
        - name: orocommerce-app-cache-pvc
          persistentVolumeClaim:
            claimName: orocommerce-app-cache-pvc
            readOnly: false
        - name: orocommerce-app-public-pvc
          persistentVolumeClaim:
            claimName: orocommerce-app-public-pvc
            readOnly: false
        - name: orocommerce-app-private-pvc
          persistentVolumeClaim:
            claimName: orocommerce-app-private-pvc
            readOnly: false