apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orocommerce-postgre
  labels:
    app: orocommerce-postgre
  namespace: orocommerce
spec:
  selector:
    matchLabels:
      app: orocommerce-postgre
  serviceName: orocommerce-postgre
  replicas: 1
  template:
    metadata:
      labels:
        app: orocommerce-postgre
    spec:
      containers:
        - name: postgre
          image: docker.io/oroinc/pgsql:17.2-alpine
          ports:
          - containerPort: 5432
            name: postgre
          env:
            - name: POSTGRES_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orocommerce-secret
                  key: ORO_DB_ROOT_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: orocommerce-secret
                  key: ORO_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: orocommerce-secret
                  key: ORO_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orocommerce-secret
                  key: ORO_DB_PASSWORD
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1000Mi"
              cpu: "1000m"
          volumeMounts:
            - name: orocommerce-postgre-pvc
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - exec pg_isready -U orodbuser -d orodb
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - -e
              - |
                exec pg_isready -U orodbuser -d orodb
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: orocommerce-postgre-pvc
      spec:
        accessModes:
          - ReadWriteOncePod
        volumeMode: Filesystem
        resources:
          requests:
            storage: 5Gi
        storageClassName: orocommerce-csi-hostpath-sc
        