# Default values for orocommerce.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

storageClass:
  name: local-storage
  provisioner: kubernetes.io/no-provisioner
  volumeBindingMode: WaitForFirstConsumer
  reclaimPolicy: Retain

envLogValue: php://stderr

persistentVolumes:
  ## PV de l'application
  appCapacity: 10Gi
  appAccessModes:
    - ReadWriteMany
    - ReadOnlyMany
  appHostPath: /orocommerce/app
  ## PV du cache de l'application
  appCacheCapacity: 10Gi
  appCacheAccessModes:
    - ReadWriteMany
    - ReadOnlyMany
  appCacheHostPath: /orocommerce/cache
  ## PV de la maintenance de l'application

  appMaintenanceCapacity: 10Gi
  appMaintenanceAccessModes:
    - ReadWriteMany
    - ReadOnlyMany
  appMaintenanceHostPath: /orocommerce/maintenance
  ## PV des opération multiples de l'application
  appMultihostOperationCapacity: 10Gi
  appMultihostOperationAccessModes:
    - ReadWriteMany
    - ReadOnlyMany
  appMultihostOperationHostPath: /orocommerce/multihost-operation
  ## PV des dossiers privés de l'application
  appPrivateCapacity: 10Gi
  appPrivateAccessModes:
    - ReadWriteMany
    - ReadOnlyMany
  appPrivateHostPath: /orocommerce/private
  ## PV des dossiers publics de l'application
  appPublicCapacity: 10Gi
  appPublicAccessModes:
    - ReadWriteMany
    - ReadOnlyMany
  appPublicHostPath: /orocommerce/public


secrets:
  protocol: https
