apiVersion: apps/v1
kind: Deployment
metadata:
  name: orocommerce-app-php-fpm
  namespace: orocommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orocommerce-app-php-fpm
  template:
    metadata:
      labels:
        app: orocommerce-app-php-fpm
    spec:
      securityContext:
        runAsUser: 2002
        runAsGroup: 2001
      containers:
        - name: orocommerce-app-php-fpm
          image: oroinc/runtime:6.1-latest
          args: ["php-fpm"]
          env:
            - name: ORO_LOG_PATH
              value: php://stderr
          envFrom:
            - secretRef: 
                name: orocommerce-secret
          ports:
            - containerPort: 9000
          livenessProbe:
            exec:
                command:
                    - /bin/sh
                    - -c
                    - php-fpm-healthcheck
            periodSeconds: 5
            initialDelaySeconds: 15
            timeoutSeconds: 30
          volumeMounts:
            - name: php-fpm-app-pvc
              mountPath: /var/www/oro
            - name: php-fpm-cache-pvc
              mountPath: /var/www/oro/var/cache
            - name: php-fpm-multihost-operation-pvc
              mountPath: /var/www/oro/var/multihost
            - name: php-fpm-maintenance-pvc
              mountPath: /var/www/oro/var/maintenance
            - name: php-fpm-public-pvc
              mountPath: /var/www/oro/public/media
            - name: php-fpm-private-pvc
              mountPath: /var/www/oro/var/data
            - name: tmp
              mountPath: /tmp
        # - name: consumer
        #   image: oroinc/runtime:6.1-latest
        #   args: ["consumer"]
        #   volumeMounts:
        #     - name: php-fpm-app-pvc
        #       mountPath: /var/www/oro
        #   envFrom:
        #     - secretRef: 
        #         name: orocommerce-secret
        # - name: cron
        #   image: oroinc/runtime:6.1-latest
        #   args: ["cron"]
        #   volumeMounts:
        #     - name: php-fpm-app-pvc
        #       mountPath: /var/www/oro
        #   envFrom:
        #     - secretRef: 
        #         name: orocommerce-secret
      initContainers:
        - name: volume-init
          image: oroinc/orocommerce-application:6.1.0
          args: ["-c", "cp -rp /var/www/oro/. /data && chown -R www-data:www-data /data"]
          volumeMounts:
          - name: php-fpm-app-pvc
            mountPath: /data
          - name: php-fpm-cache-pvc
            mountPath: /data/var/cache
          - name: php-fpm-public-pvc
            mountPath: /data/public/media
          - name: php-fpm-private-pvc
            mountPath: /data/var/private
          securityContext:
            runAsUser: 0
        - name: restore
          image: oroinc/orocommerce-application-init-fr:6.1.0
          command: ["sh", "-c", "until nc -z orocommerce-db 5432; do echo \"Waiting for database connection...\"; sleep 1; done && docker-entrypoint.sh restore"]
          envFrom:
            - secretRef: 
                name: orocommerce-secret
          volumeMounts:
          - name: php-fpm-app-pvc
            mountPath: /var/www/oro
          - name: php-fpm-cache-pvc
            mountPath: /var/www/oro/var/cache
          - name: php-fpm-public-pvc
            mountPath: /var/www/oro/public/media
          - name: php-fpm-private-pvc
            mountPath: /var/www/oro/var/data
      volumes:
        - name: php-fpm-app-pvc
          persistentVolumeClaim:
            claimName: php-fpm-app-pvc
            readOnly: false
        - name: php-fpm-cache-pvc
          persistentVolumeClaim:
            claimName: php-fpm-cache-pvc
            readOnly: false
        - name: php-fpm-multihost-operation-pvc
          persistentVolumeClaim:
            claimName: php-fpm-multihost-operation-pvc
            readOnly: false
        - name: php-fpm-maintenance-pvc
          persistentVolumeClaim:
            claimName: php-fpm-maintenance-pvc
            readOnly: false
        - name: php-fpm-public-pvc
          persistentVolumeClaim:
            claimName: php-fpm-public-pvc
            readOnly: false
        - name: php-fpm-private-pvc
          persistentVolumeClaim:
            claimName: php-fpm-private-pvc
            readOnly: false
        - name: tmp
          emptyDir: {}