apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-fpm-app-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /oro-php-fpm/app