apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-fpm-cache-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /oro-php-fpm/cache
  claimRef:
    name: php-fpm-cache-pvc
    namespace: default