apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-fpm-maintenance-pv
  labels:
    name: php-fpm-maintenance-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /orocommerce/php-fpm/maintenance