apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-fpm-multihost-operation-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /orocommerce/php-fpm/multihost
  claimRef:
    name: php-fpm-multihost-operation-pvc
    namespace: default