apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-fpm-multihost-operation-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /oro-php-fpm/multihost