apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-fpm-private-storage-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /orocommerce/php-fpm/data
  claimRef:
    name: php-fpm-private-storage-pvc
    namespace: default