apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-fpm-maintenance-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local