apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-fpm-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local
  selector:
    matchLabels:
      name: php-fpm-cache-pv