apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orocommerce-cron
  labels:
    app: orocommerce-cron
spec:
  selector:
    matchLabels:
      app: orocommerce-cron
  serviceName: orocommerce-app-php-fpm
  replicas: 1
  template:
    metadata:
      labels:
        app: orocommerce-cron
    spec:
      containers:
        - name: cron
          image: oroinc/runtime:6.1-latest
          args: ["cron"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 2002
            runAsGroup: 2001
          volumeMounts:
            - name: php-fpm-app-pvc
              mountPath: /var/www/oro
            - name: php-fpm-cache-pvc
              mountPath: /var/www/oro/var/cache
            - name: php-fpm-multihost-operation-pvc
              mountPath: /var/www/oro/var/multihost
            - name: php-fpm-maintenance-pvc
              mountPath: /var/www/oro/var/maintenance
            - name: php-fpm-public-storage-pvc
              mountPath: /var/www/oro/public/media
            - name: php-fpm-private-storage-pvc
              mountPath: /var/www/oro/var/data
          envFrom:
            - secretRef: 
                name: orocommerce-secret
      volumes:
        - name: php-fpm-app-pvc
          persistentVolumeClaim:
            claimName: php-fpm-app-pvc
        - name: php-fpm-cache-pvc
          persistentVolumeClaim:
            claimName: php-fpm-cache-pvc
        - name: php-fpm-multihost-operation-pvc
          persistentVolumeClaim:
            claimName: php-fpm-multihost-operation-pvc
        - name: php-fpm-maintenance-pvc
          persistentVolumeClaim:
            claimName: php-fpm-maintenance-pvc
        - name: php-fpm-public-storage-pvc
          persistentVolumeClaim:
            claimName: php-fpm-public-storage-pvc
        - name: php-fpm-private-storage-pvc
          persistentVolumeClaim:
            claimName: php-fpm-private-storage-pvc
        
        