apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orocommerce-cron
  labels:
    app: orocommerce-cron
  namespace: orocommerce
spec:
  selector:
    matchLabels:
      app: orocommerce-cron
  serviceName: orocommerce-app-php-fpm
  replicas: 1
  template:
    metadata:
      labels:
        app: orocommerce-cron
    spec:
      containers:
        - name: cron
          image: oroinc/runtime:6.1-latest
          args: ["cron"]
          volumeMounts:
            - name: php-fpm-app-pvc
              mountPath: /var/www/oro
          envFrom:
            - secretRef: 
                name: orocommerce-secret
      volumes:
        - name: php-fpm-app-pvc
          persistentVolumeClaim:
            claimName: php-fpm-app-pvc
        
        