apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm-app
  template:
    metadata:
      labels:
        app: php-fpm-app
    spec:
      containers:
        - name: php-fpm
          image: oroinc/runtime:6.1-latest
          args: ["php-fpm"]
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: oro-env
            - secretRef:
                name: oro-secrets
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"