apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-fpm-cache-pv
  labels:
    name: php-fpm-cache-pv
  namespace: orocommerce
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /orocommerce/php-fpm/cache