apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-fpm-multihost-operation-pvc
  namespace: orocommerce
spec:
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local
  selector:
    matchLabels:
      name: php-fpm-multihost-operation-pv