apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-fpm-public-pvc
  namespace: orocommerce
spec:
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      name: php-fpm-public-pv