apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    name: nginx-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /orocommerce/nginx